WARNING | 2024-09-19 17:15:20,102 | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\maxts\PyChar\Home\Project_homework\tests_12_4.py", line 23, in test_run
    test_run = rt.Runner(('Denis', 'Alex'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxts\PyChar\Home\Project_homework\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано tuple
WARNING | 2024-09-19 17:15:20,104 | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\maxts\PyChar\Home\Project_homework\tests_12_4.py", line 12, in test_walk
    test_run = rt.Runner('Denis', -5)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maxts\PyChar\Home\Project_homework\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
